apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-empsys-backend
  template:
    metadata:
      labels:
        app: go-empsys-backend
    spec:
      containers:
      - name: backend
        image: pushpak4/backend:v3
        env:
        - name: DB_HOST
          value: postgres-service
        - name: DB_USER
          value: pushpak1
        - name: DB_PASSWORD
          value: pushpak123
        - name: DB_NAME
          value: Empsys-DB
        - name: DB_PORT
          value: "5432"
        - name: ALLOWED_ORIGINS
          value: "*"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: go-empsys-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32502
  type: NodePort
