apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactempsys
  template:
    metadata:
      labels:
        app: reactempsys
    spec:
      containers:
      - name:  reactjs-frontend
        image: pushpak4/frontend:1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: reactempsys
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      #nodePort: 32000
  type: LoadBalancer
