apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: Empsys-DB
        - name: POSTGRES_USER
          value: pushpak1
        - name: POSTGRES_PASSWORD
          value: pushpak123
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgresdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
